### ISSUE TITLE
Improve Javadoc

### ISSUE THREAD

**Issue by alexpartsch** [DDS-GmbH/jocument#31]
### TODOs
- [x] Document all public facing classes and their instance and static methods.
- [x] Decide on uniform versioning for the `@since` Javadoc annotation, always use the date added.
- [ ] Build and include javadoc and sources JARs to Github Packages. (look into jlibvips, already doing it there)

**Comment by AntonOellerer** [comment]
`@since` should always use the date the class was added
